/**
 * Comprehensive Email Templates for DataProfessor Dashboard
 * Phase 4: Enhanced Communication & Notifications
 */

export interface EmailTemplate {
  subject: string;
  html: string;
}

export interface TemplateVariables {
  professorName?: string;
  studentName?: string;
  taskName?: string;
  projectName?: string;
  dueDate?: string;
  weekStart?: string;
  totalHours?: number;
  daysPastDue?: number;
  daysSinceActivity?: number;
  dropPercentage?: number;
  scheduledHours?: number;
  completedTasks?: number;
  overdueTasks?: number;
  productivityScore?: number;
  reason?: string;
  customMessage?: string;
  dashboardUrl?: string;
}

/**
 * Generate email template with variables replaced
 */
export function generateEmailFromTemplate(
  template: EmailTemplate, 
  variables: TemplateVariables
): EmailTemplate {
  let subject = template.subject;
  let html = template.html;
  
  // Replace all variables in both subject and html
  Object.entries(variables).forEach(([key, value]) => {
    const placeholder = `{${key}}`;
    subject = subject.replace(new RegExp(placeholder, 'g'), String(value || ''));
    html = html.replace(new RegExp(placeholder, 'g'), String(value || ''));
  });
  
  return { subject, html };
}

/**
 * Email Templates for Students
 */
export const StudentEmailTemplates = {
  TASK_ASSIGNED: {
    subject: '🎯 New Task Assigned: {taskName}',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <div style="background-color: white; padding: 30px; border-radius: 8px; border-left: 4px solid #3b82f6;">
          <h2 style="color: #1f2937; margin-bottom: 20px;">🎯 New Task Assigned</h2>
          
          <div style="background-color: #eff6ff; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
            <h3 style="margin: 0 0 10px 0; color: #1e40af;">Task Details</h3>
            <p><strong>Task:</strong> {taskName}</p>
            <p><strong>Project:</strong> {projectName}</p>
            <p><strong>Due Date:</strong> {dueDate}</p>
          </div>
          
          <p style="color: #4b5563; line-height: 1.6;">
            You have been assigned a new task by your professor. Please log into the DataProfessor Dashboard to view full details, requirements, and submit your work when complete.
          </p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="{dashboardUrl}" 
               style="background-color: #3b82f6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              View Task Details
            </a>
          </div>
          
          <p style="font-size: 12px; color: #6b7280; margin-top: 20px; border-top: 1px solid #e5e7eb; padding-top: 15px;">
            This email was generated by DataProfessor Dashboard. If you have questions, contact your professor directly.
          </p>
        </div>
      </div>
    `
  },

  TASK_OVERDUE: {
    subject: '⚠️ Overdue Task Reminder: {taskName}',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <div style="background-color: white; padding: 30px; border-radius: 8px; border-left: 4px solid #ef4444;">
          <h2 style="color: #dc2626; margin-bottom: 20px;">⚠️ Task Overdue</h2>
          
          <div style="background-color: #fef2f2; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
            <h3 style="margin: 0 0 10px 0; color: #dc2626;">Overdue Task</h3>
            <p><strong>Task:</strong> {taskName}</p>
            <p><strong>Project:</strong> {projectName}</p>
            <p><strong>Days Past Due:</strong> {daysPastDue} days</p>
          </div>
          
          <p style="color: #4b5563; line-height: 1.6;">
            This task is now <strong>{daysPastDue} days overdue</strong>. Please complete this task as soon as possible or contact your professor if you're experiencing difficulties.
          </p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="{dashboardUrl}" 
               style="background-color: #ef4444; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              Complete Task Now
            </a>
          </div>
          
          <p style="font-size: 12px; color: #6b7280; margin-top: 20px; border-top: 1px solid #e5e7eb; padding-top: 15px;">
            This email was generated by DataProfessor Dashboard.
          </p>
        </div>
      </div>
    `
  },

  SCHEDULE_APPROVED: {
    subject: '✅ Schedule Approved for Week of {weekStart}',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <div style="background-color: white; padding: 30px; border-radius: 8px; border-left: 4px solid #10b981;">
          <h2 style="color: #059669; margin-bottom: 20px;">✅ Schedule Approved</h2>
          
          <div style="background-color: #ecfdf5; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
            <h3 style="margin: 0 0 10px 0; color: #059669;">Approved Schedule</h3>
            <p><strong>Week of:</strong> {weekStart}</p>
            <p><strong>Total Hours:</strong> {totalHours}</p>
          </div>
          
          <p style="color: #4b5563; line-height: 1.6;">
            Your schedule has been reviewed and approved by your professor. You can now proceed with your planned lab activities for this week.
          </p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="{dashboardUrl}" 
               style="background-color: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              View Schedule
            </a>
          </div>
        </div>
      </div>
    `
  },

  SCHEDULE_REJECTED: {
    subject: '❌ Schedule Needs Revision for Week of {weekStart}',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <div style="background-color: white; padding: 30px; border-radius: 8px; border-left: 4px solid #f59e0b;">
          <h2 style="color: #d97706; margin-bottom: 20px;">❌ Schedule Needs Revision</h2>
          
          <div style="background-color: #fffbeb; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
            <h3 style="margin: 0 0 10px 0; color: #d97706;">Feedback Required</h3>
            <p><strong>Week of:</strong> {weekStart}</p>
            <p><strong>Reason:</strong> {reason}</p>
          </div>
          
          <p style="color: #4b5563; line-height: 1.6;">
            Your professor has requested revisions to your submitted schedule. Please review the feedback above and resubmit your updated schedule.
          </p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="{dashboardUrl}" 
               style="background-color: #f59e0b; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              Revise Schedule
            </a>
          </div>
        </div>
      </div>
    `
  },

  PRODUCTIVITY_ENCOURAGEMENT: {
    subject: '📈 Great Work This Week!',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <div style="background-color: white; padding: 30px; border-radius: 8px; border-left: 4px solid #8b5cf6;">
          <h2 style="color: #7c3aed; margin-bottom: 20px;">📈 Great Work This Week!</h2>
          
          <div style="background-color: #f3f4f6; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
            <h3 style="margin: 0 0 10px 0; color: #7c3aed;">Your Progress</h3>
            <p><strong>Tasks Completed:</strong> {completedTasks}</p>
            <p><strong>Productivity Score:</strong> {productivityScore}%</p>
          </div>
          
          <p style="color: #4b5563; line-height: 1.6;">
            Excellent work! You're showing great productivity and progress on your projects. Keep up the momentum!
          </p>
          
          {customMessage}
        </div>
      </div>
    `
  },

  SCHEDULE_REMINDER: {
    subject: '📋 Reminder: Submit Your Weekly Schedule',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <div style="background-color: white; padding: 30px; border-radius: 8px; border-left: 4px solid #3b82f6;">
          <h2 style="color: #1d4ed8; margin-bottom: 20px;">📋 Schedule Submission Reminder</h2>
          
          <p style="color: #4b5563; line-height: 1.6;">
            Hi {studentName},<br><br>
            
            This is a friendly reminder to submit your schedule for the week of {weekStart}. 
            Please submit it as soon as possible so your professor can review and approve your planned activities.
          </p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="{dashboardUrl}" 
               style="background-color: #3b82f6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              Submit Schedule
            </a>
          </div>
        </div>
      </div>
    `
  }
};

/**
 * Email Templates for Professors
 */
export const ProfessorEmailTemplates = {
  PROJECT_ASSIGNED_CONFIRMATION: {
    subject: '✅ Project Assignment Confirmed: {studentName} → {projectName}',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <div style="background-color: white; padding: 30px; border-radius: 8px; border-left: 4px solid #10b981;">
          <h2 style="color: #059669; margin-bottom: 20px;">✅ Project Assignment Confirmed</h2>
          
          <div style="background-color: #ecfdf5; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
            <p><strong>{studentName}</strong> has been successfully assigned to project:</p>
            <h3 style="margin: 10px 0; color: #059669;">{projectName}</h3>
          </div>
          
          <p style="color: #4b5563; line-height: 1.6;">
            The student has been automatically notified via email and can now view the project details in their dashboard.
          </p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="{dashboardUrl}" 
               style="background-color: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              View Project Details
            </a>
          </div>
        </div>
      </div>
    `
  },

  SCHEDULE_SUBMITTED: {
    subject: '📋 Schedule Submitted for Review: {studentName} - Week of {weekStart}',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <div style="background-color: white; padding: 30px; border-radius: 8px; border-left: 4px solid #3b82f6;">
          <h2 style="color: #1d4ed8; margin-bottom: 20px;">📋 Schedule Awaiting Review</h2>
          
          <div style="background-color: #eff6ff; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
            <h3 style="margin: 0 0 10px 0; color: #1d4ed8;">Submission Details</h3>
            <p><strong>Student:</strong> {studentName}</p>
            <p><strong>Week of:</strong> {weekStart}</p>
            <p><strong>Total Hours:</strong> {totalHours}</p>
          </div>
          
          <p style="color: #4b5563; line-height: 1.6;">
            A student has submitted their weekly schedule for your review. Please approve or provide feedback for any necessary revisions.
          </p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="{dashboardUrl}" 
               style="background-color: #3b82f6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              Review Schedule
            </a>
          </div>
        </div>
      </div>
    `
  },

  STUDENT_INACTIVE_ALERT: {
    subject: '🔄 Student Activity Alert: {studentName} ({daysSinceActivity} days inactive)',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <div style="background-color: white; padding: 30px; border-radius: 8px; border-left: 4px solid #f59e0b;">
          <h2 style="color: #d97706; margin-bottom: 20px;">🔄 Student Activity Alert</h2>
          
          <div style="background-color: #fffbeb; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
            <h3 style="margin: 0 0 10px 0; color: #d97706;">Inactive Student</h3>
            <p><strong>Student:</strong> {studentName}</p>
            <p><strong>Days Since Activity:</strong> {daysSinceActivity} days</p>
          </div>
          
          <p style="color: #4b5563; line-height: 1.6;">
            <strong>{studentName}</strong> has been inactive for {daysSinceActivity} days. No tasks completed, schedules submitted, or system activity detected.
            <br><br>
            <strong>Recommended Actions:</strong>
            <br>• Send a check-in email
            <br>• Schedule a one-on-one meeting
            <br>• Review their current workload
          </p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="{dashboardUrl}" 
               style="background-color: #f59e0b; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              View Student Progress
            </a>
          </div>
        </div>
      </div>
    `
  },

  PRODUCTIVITY_DECLINE_ALERT: {
    subject: '📉 Productivity Alert: {studentName} - {dropPercentage}% decline',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <div style="background-color: white; padding: 30px; border-radius: 8px; border-left: 4px solid #ef4444;">
          <h2 style="color: #dc2626; margin-bottom: 20px;">📉 Productivity Decline Alert</h2>
          
          <div style="background-color: #fef2f2; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
            <h3 style="margin: 0 0 10px 0; color: #dc2626;">Performance Change</h3>
            <p><strong>Student:</strong> {studentName}</p>
            <p><strong>Productivity Drop:</strong> {dropPercentage}%</p>
            <p><strong>Current Score:</strong> {productivityScore}%</p>
          </div>
          
          <p style="color: #4b5563; line-height: 1.6;">
            AI analysis has detected a significant productivity decline for <strong>{studentName}</strong>. 
            This may indicate potential challenges that need attention.
            <br><br>
            <strong>Suggested Actions:</strong>
            <br>• Reach out for a personal check-in
            <br>• Review current project workload
            <br>• Assess if additional support is needed
          </p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="{dashboardUrl}" 
               style="background-color: #ef4444; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              View Detailed Analysis
            </a>
          </div>
        </div>
      </div>
    `
  },

  MULTIPLE_OVERDUE_TASKS: {
    subject: '⚠️ Multiple Overdue Tasks: {studentName} ({overdueTasks} tasks)',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <div style="background-color: white; padding: 30px; border-radius: 8px; border-left: 4px solid #ef4444;">
          <h2 style="color: #dc2626; margin-bottom: 20px;">⚠️ Multiple Overdue Tasks Alert</h2>
          
          <div style="background-color: #fef2f2; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
            <h3 style="margin: 0 0 10px 0; color: #dc2626;">Task Status</h3>
            <p><strong>Student:</strong> {studentName}</p>
            <p><strong>Overdue Tasks:</strong> {overdueTasks}</p>
          </div>
          
          <p style="color: #4b5563; line-height: 1.6;">
            <strong>{studentName}</strong> has {overdueTasks} overdue tasks. This may indicate workload management issues or other challenges.
            <br><br>
            <strong>Recommended Actions:</strong>
            <br>• Review task priorities with the student
            <br>• Consider deadline adjustments if appropriate
            <br>• Provide additional guidance or resources
          </p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="{dashboardUrl}" 
               style="background-color: #ef4444; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              View Task Details
            </a>
          </div>
        </div>
      </div>
    `
  }
};

/**
 * Quick Communication Templates for Professors
 */
export const CommunicationTemplates = {
  PROGRESS_CHECK_IN: {
    subject: 'Weekly Progress Check-in',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <p>Hi {studentName},</p>
        
        <p>I'd like to get an update on your progress this week. Please provide:</p>
        
        <ol>
          <li>Tasks completed this week</li>
          <li>Current challenges or roadblocks</li>
          <li>Goals for next week</li>
          <li>Any support or resources needed</li>
        </ol>
        
        <p>Please reply by email or we can schedule a brief meeting if you prefer.</p>
        
        <p>Best regards,<br>
        {professorName}</p>
      </div>
    `
  },

  GENTLE_REMINDER: {
    subject: 'Friendly Reminder - {taskName}',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <p>Hi {studentName},</p>
        
        <p>Just a friendly reminder about "<strong>{taskName}</strong>" which is due on {dueDate}.</p>
        
        <p>If you need any assistance, have questions, or anticipate any delays, please let me know as soon as possible.</p>
        
        <p>Best regards,<br>
        {professorName}</p>
      </div>
    `
  },

  MEETING_REQUEST: {
    subject: 'Meeting Request - Lab Progress Discussion',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <p>Hi {studentName},</p>
        
        <p>I'd like to schedule a meeting to discuss your current progress and any support you might need.</p>
        
        <p>Please let me know your availability for a 30-minute meeting this week or next.</p>
        
        <p>Topics we'll cover:</p>
        <ul>
          <li>Current project status</li>
          <li>Upcoming deadlines and priorities</li>
          <li>Any challenges or questions</li>
          <li>Goals and planning</li>
        </ul>
        
        <p>Best regards,<br>
        {professorName}</p>
      </div>
    `
  },

  CUSTOM_MESSAGE: {
    subject: '{customMessage}',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <p>Hi {studentName},</p>
        
        <p>{customMessage}</p>
        
        <p>Best regards,<br>
        {professorName}</p>
      </div>
    `
  }
};